apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medibrowserr-data
  labels:
    app.kubernetes.io/name: medibrowserr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: your-storage-class
